### ISSUE TITLE
Pandas warnings

### ISSUE THREAD

**Issue by ncfirth** [beOn/cili#14]
Pandas throws various FutureWarning messages from deprecated functions. Are you still maintaining cili? I'm happy to make the changes and make a PR if you are, otherwise I'll fork.

**Comment by beOn** [comment]
Submit a PR and I'll take a look! Thanks for the catch!

**Comment by beOn** [comment]
Yeah, that's super annoying. Would be happy to look at a PR!

**Comment by ncfirth** [comment]
I half did this, but I haven't quite finished. The master branch is now Python 3 right? So I'll work off that.

**Comment by beOn** [comment]
Yup. Maintaining python 2.7 support, though. But do it for 3 and I’ll handle backwards compatibility.

**Comment by harrisonford** [comment]
One deprecated function used in util.py:270 using convert_objects. Are you guys on this yet ? Once I finish the dataset processing I could help with a PR too. Also using on Python 3.

**Comment by beOn** [comment]
On it, but swamped and moving slowly.

**Comment by beOn** [comment]
Addressed by #16
