### ISSUE TITLE
Extract data based on variable time ranges

### ISSUE THREAD

**Issue by HanZhang-psych** [beOn/cili#19]
Hi all,

First of all, this is a great project! I was wondering if there is any way to extract data based on variable time ranges. For example, I would like to extract all sample data during each trial, but the duration of each trial was not constant.

Thank you!

**Comment by beOn** [comment]
Glad you've found it useful!

The Samples object is a pandas DataFrame, so you can index it as you would any other pandas DataFrame. If you've tried that and you're having trouble, please post your code and I'll see if I can help!
