### ISSUE TITLE
extract_event_ranges keyerror

### ISSUE THREAD

**Issue by tomwallis** [beOn/cili#3]
My todo list for today involved "write script to parse eyelink data files". Happily, I discovered the existence of your package!

However, I get an error when using `extract_event_ranges` that's possibly related to [this question](https://github.com/beOn/cili/issues/2).

Using a datafile sampled at 250 Hz, I get the following error on `extract_event_ranges`:

``` python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-8f9980caae01> in <module>()
      1 samps, events = load_eyelink_dataset("practice_experiment-1_sub_eye_session_1.asc")
      2 # extract event based ranges.
----> 3 ranges = extract_event_ranges(samps, events.EFIX, end_offset=19)

/Users/tomwallis/miniconda3/envs/py27/lib/python2.7/site-packages/cili/extract.pyc in extract_event_ranges(samples, events_dataframe, start_offset, end_offset, round_indices, borrow_attributes)
     49     r_times.columns = ['last_onset']
     50     # find the number of samples per range... right now, we assume they're all equal
---> 51     r_len = samples.index.get_loc(r_times.last_onset.iloc[0]) - samples.index.get_loc(r_times.index[0]) + 1
     52     # we're going to make a df with a hierarchical index.
     53     # There's an annoying assumption hidden here!

/Users/tomwallis/miniconda3/envs/py27/lib/python2.7/site-packages/pandas/core/index.pyc in get_loc(self, key)
   1400         loc : int if unique index, possibly slice or mask if not
   1401         """
-> 1402         return self._engine.get_loc(_values_from_object(key))
   1403 
   1404     def get_value(self, series, key):

pandas/index.pyx in pandas.index.IndexEngine.get_loc (pandas/index.c:3812)()

pandas/index.pyx in pandas.index.IndexEngine.get_loc (pandas/index.c:3692)()

pandas/hashtable.pyx in pandas.hashtable.Int64HashTable.get_item (pandas/hashtable.c:7201)()

pandas/hashtable.pyx in pandas.hashtable.Int64HashTable.get_item (pandas/hashtable.c:7139)()

KeyError: 10687429
```

The script to reproduce the error is 

``` python
import numpy as np
from cili.util import load_eyelink_dataset
from cili.extract import extract_event_ranges

samps, events = load_eyelink_dataset("practice_experiment-1_sub_eye_session_1.asc")
# extract event based ranges.
ranges = extract_event_ranges(samps, events.EFIX, end_offset=19)

```

File to reproduce the bug is found [here](https://github.com/tomwallis/attachments/blob/master/practice_experiment-1_sub_eye_session_1.asc).

**Comment by beOn** [comment]
Thanks for the report - especially for including the data file! I'll take a look at this over the weekend, if not sooner.

**Comment by tomwallis** [comment]
I don't have time to look at it now, but I think I just realised why this is happening. You are looking in the samples index for an integer timestamp that corresponds with the timestamp from an event. If the sample rate is 1000 Hz that's fine --- there will always be a sample index corresponding to any possible event timestamp. When the sample rate is lower than that (as in my data file), it's possible that event timestamps will occur between eye samples.

You need to take the event timestamp and seek the next sample that actually occurs in the sample index, then start the extraction from there. You will also have to correct the `start_offset` and `end_offset` behaviour.

I might get a chance to work on this tomorrow.

**Comment by beOn** [comment]
Ah, yes, that was it! Shouldn't be too much of a pain to fix. Looks like it's going to be a busy weekend...

Ben

**Comment by beOn** [comment]
So, fixing this... just a heads up that in this dataset, for some reason the first event claims to begin before the first sample. Weird. Anyhow, I'm going to catch this and throw an exception, since it's a little too weird a thing for me to build in a hidden fix for.

**Comment by tomwallis** [comment]
Not so weird, if you consider that the eyelink is downsampling by only
saving every Nth sample. So the event could happen on some time point prior
to the first sample being _saved_ (not recorded).

You'd think they would always save the first sample they record, but I
guess not.

**Comment by beOn** [comment]
Okay, fix is in as of commit 5aa9336f6b6087b9ca520840aaf23f02b59e1fdb. Note that because the first event in your EFIX event set starts before the first sample, and this now throws an exception, you have to omit that event form the list. Also, note that the end_offset parameter's units are milliseconds, so you're getting very few samples back... nevertheless, the following now works for me:

``` python
import numpy as np
from cili.util import load_eyelink_dataset
from cili.extract import extract_event_ranges
# load stuff
samps, events = load_eyelink_dataset("/Volumes/Purkinje/temp/data.asc")
# extract event based ranges.
ranges = extract_event_ranges(samps, events.EFIX.iloc[1:], end_offset=19)
```

Printing ranges gets me...

```
(Pdb) ranges
               x_l    y_l  pup_l    x_r    y_r  pup_r  orig_idx
event onset                                                    
0     0      928.0  603.7   7285  960.2  589.7   7221  10688942
      1      928.1  602.1   7289  959.4  590.6   7224  10688946
      2      928.2  601.7   7293  957.5  588.8   7227  10688950
      3      927.6  601.3   7300  957.1  585.6   7229  10688954
      4      927.5  600.8   7304  957.1  588.8   7235  10688958
1     0      928.0  603.7   7285  960.2  589.7   7221  10688942
      1      928.1  602.1   7289  959.4  590.6   7224  10688946
      2      928.2  601.7   7293  957.5  588.8   7227  10688950
      3      927.6  601.3   7300  957.1  585.6   7229  10688954
      4      927.5  600.8   7304  957.1  588.8   7235  10688958
... etc.
```

So I think this addresses your issue. Let me know if not.

In working on this, I realized that this method is just stupid. I should just explicitly take a desired sample count, so that you can explicitly control the shape of the data returned. So pending your feedback I'm going to add another method that does that, then cut a release.

**Comment by beOn** [comment]
w.r.t. early events - agreed. I guess what I was trying to say is that I'm not going to transparently remove one of the events from the list just because I don't have samples for it, and don't really see a good way to leave it in (other than NAs, perhaps?). So I'm just gonna throw an exception, and leave it to the user to prune their events.

Perhaps this could be cleaned up a bit with an option in the asc parser to ignore events beginning before the first sample. With that enabled by default, the chances of anyone running into this problem in most simple use cases would be pretty low.

**Comment by beOn** [comment]
Eh, actually, I think I'm going to just automatically adjust the start times of any event beginning before the first sample to the first sample time... and similarly adjust events ending after the last sample.

**Comment by tomwallis** [comment]
Why not just take the next occurring sample after the event start?

**Comment by beOn** [comment]
Haha, take a look at 2882d1ca2737c1de65df83cb58d0228f3605db50. It does exactly that.

(as of this change, your original code should work)

**Comment by tomwallis** [comment]
Ah ok. Didn't look at the code yet. About to go to bed.

Thanks for the fixes. Will pull the dev version tomorrow and test.

**Comment by beOn** [comment]
Tübingen was the first place I gave a scientific presentation :)

**Comment by beOn** [comment]
Eh, there are a couple little mistakes. Fixing and adding a new method...

**Comment by beOn** [comment]
Okay, check out the latest master (91bea4d64efb319ef37f05f458ce9e8915279d2b). I added extract_events, which you can use like so to extract a set number of samples per event:

``` python
ranges = extract_events(samps, events.EFIX, duration=5)
```

...or like so to extract some uniform number of samples per event based on the duration of the first event (like the current implementation):

``` python
ranges = extract_events(samps, events.EFIX, duration=19, units='time')
```

Note that there is also an 'onset' parameter, and that the interpretation of 'onset' and 'duration' depend upon the 'units' setting. It's all explained (hopefully) in the extract_events method notes.

**Comment by tomwallis** [comment]
Sorry for the delay. Getting to look at this now.
1. `extract_event_ranges` now works for me. Bug fixed. 
2. If I understand correctly, you are intending that `extract_events` will replace `extract_event_ranges`?

I tested both revised functions on my dataset and both seem to work (at least, not returning errors; I haven't checked if the values make sense). 

Incidentally, I changed the calling for `extract_events` slightly (see [this pull request](https://github.com/beOn/cili/pull/5)). Basically, I didn't understand the need for the upper case values; I think it's simpler to provide either 'time' or 'samples' as the units. I also included an invalid units check.

**Comment by tomwallis** [comment]
Second question on both functions: the docs state that the `events` dataframe must contain a column called `duration`. Why? This column doesn't appear to be used by the function as far as I can see, and is confusing with the additional parameter `duration`.

If the `duration` parameter is not used in `extract_events` I would suggest removing it from the docstring. It doesn't matter whether or not the `events` dataframe you pass contains a series called `duration` or not.

**Comment by jtmbeta** [comment]
The duration column is for when you wish to extract trials of variable lengths (not currently supported), something I hope to get working on shortly.

**Comment by tomwallis** [comment]
Ah ok, that makes sense.

I'm closing this bug report now, since the error with the 250 Hz sampling seems to be fixed.
