### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by tomwallis** [beOn/cili#4]
I can see this package becoming an important part of my analysis workflow. I prefer to use Python 3, so I would be willing to spend some time making this Python 3 compatible (it isn't). Before I do that, it would be really helpful if the package included some unit tests. This is a good idea more generally.

I'm happy to help with this, but I would need you to upload one or two small test data files to the repository, in whatever formats you want to support (ideally less than 1 MB). Then, we can write test functions that
- run `cili` functions on the input data
- check the output against "true" output files, which we save to the repository in development. These would be outputs that are "checked" in some sense -- you are happy that they are the outputs you want.

The test functions can be run automatically with `nose`, and if any new code (e.g., making things Python 3 compatible) breaks the desired behaviour, we know about it immediately. If you get a chance on the weekend, maybe you can upload some test data and maybe desired tests?

**Comment by beOn** [comment]
I'll try to get to that this weekend, but it might take a little while... just started in a new lab :).

In general, though, I wholeheartedly agree, and would be happy to work with you to get some reasonable unit tests up and running. It seems like we can do the Python 3 update and the unit test update in parallel - we just won't merge the P3 stuff into master before the unit tests are working and passing on that branch.

**Comment by beOn** [comment]
Alright, I am officially in search of a comprehensive set of test data files!

**Comment by jtmbeta** [comment]
Here's one. Hope it's useful. Monocular 1000hz recording with EyeLink 1000. The subject tracks a blue ellipse around the screen as it follows three different sinusoidal patterns. It's a short and simple routine that can assist with correcting the gaze dependant measurement error in pupil size. If this isn't what you meant by test data files then let me know. I have more data but the files are very large.

https://www.dropbox.com/s/ogqcr77bp6c1gd2/EL_1000hz_monoL.asc?dl=0

**Comment by beOn** [comment]
This is exactly what we need! It’s okay if they’re cropped down to size… we don’t need a lot of data, just for it to be correctly formatted. If you have some files that would be great, but are too large, just delete everything after the first 10s - we can run all of our tests on that time range.

Ben

**Comment by beOn** [comment]
Wow, the people over at SR Research really came through - they have provided us with a comprehensive set of test files, which I will be adding to the repo over the weekend!

**Comment by tomwallis** [comment]
I just pulled from your repo to get the unit tests, and running `nosetests` gives me a whole bunch of errors and failures. Are these tests passing on your system yet?

``` Python
ERROR: tests.test_extract.test_timeunit_extract_samplecount_2000
ValueError: Length mismatch: Expected axis has 12024 elements, new values have 12012 elements

ERROR: tests.test_extract.test_sampleunit_extract_samplecount_2000
ValueError: Length mismatch: Expected axis has 4224 elements, new values have 4200 elements

ERROR: tests.test_extract.sc_samp_test
TypeError: sc_samp_test() takes at least 3 arguments (0 given)

ERROR: tests.test_extract.sc_time_test
TypeError: sc_time_test() takes at least 4 arguments (0 given)

ERROR: tests.test_extract.test_timeunit_extract_underbounds
ValueError: at least one event range starts before the first sample

ERROR: tests.test_util.test_load_txt_convenience
NotImplementedError

ERROR: tests.test_util.test_load_asc_monoRemote250
KeyError: 'onset'

ERROR: tests.test_util.test_load_asc_monoRemote500
KeyError: 'onset'

ERROR: tests.test_util.test_monoRemote250_cols
KeyError: 'onset'

ERROR: tests.test_util.test_monoRemote500_cols
KeyError: 'onset'

ERROR: tests.test_util.test_mono2000_idx
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

FAIL: tests.test_extract.test_timeunit_extract_samplecount_250
AssertionError: 1000 != 1008

FAIL: tests.test_extract.test_timeunit_extract_samplecount_500
AssertionError: 2750 != 2761

FAIL: tests.test_extract.test_timeunit_extract_samplecount_1000
AssertionError: 4500 != 4509

FAIL: tests.test_extract.test_negative_duration
AssertionError: test_negative_duration() did not raise ValueError
```

What's the status on these? Should they be passing?

**Comment by beOn** [comment]
Nope - those are real failures. There are a few more tests to implement, then I’ll get them all passing before cutting another build. Gotta finish the semester first, though. I should be returning to this over the next week or two.

Ben

**Comment by tomwallis** [comment]
Ok great. Any recommendations on reliability? I'm currently using `cili.util.load_eyelink_dataset` and `cili.extract.extract_events` for parsing some data I'm working on. My internal checks pass. Are there any bugs you're aware of affecting these functions?

**Comment by beOn** [comment]
No bugs I’m aware of. Internal checks are wise, at this point, but hopefully not necessary for long. Thanks for your patience!

Ben

**Comment by beOn** [comment]
The coverage could be better, but there are a reasonable number of unit tests at this point. Closing.
